matrix:
  include:
    - os: linux
      env:
        - BUILD_TARGET=android_cmake
        - ANDROID_HOME=/usr/local/android-sdk
      language: android
      sudo: true
      #android:
      #  components:
      #    - tools
      #    - platform-tools
      #    - build-tools-25.0.2
      #    - android-25
      #before_script:
      #  - yes | ${ANDROID_HOME}/tools/bin/sdkmanager "tools" > /dev/null 2>&1
      #  - yes | ${ANDROID_HOME}/tools/bin/sdkmanager "platforms;android-25" > /dev/null 2>&1
      #  - yes | ${ANDROID_HOME}/tools/bin/sdkmanager "extras;android;m2repository" > /dev/null 2>&1
      #  - yes | ${ANDROID_HOME}/tools/bin/sdkmanager "extras;google;m2repository" > /dev/null 2>&1
      #  - yes | ${ANDROID_HOME}/tools/bin/sdkmanager "ndk-bundle" > /dev/null 2>&1
      #install:
        #- travis_retry sudo apt-get install ninja-build

before_install:
  - travis/before-install.sh
  - frameworks/runtime-src/proj.android/app/get_environment.sh

script:
  - travis/run-script.sh

env:
  - COCOS2DX_VERSION=cocos2d-x-3.17.1
  - COCOS2DX_ROOT=$HOME/$COCOS2DX_VERSION

cache: 
  bundler: true
  directories:
    - $COCOS2DX_ROOT
