matrix:
  include:
    - os: linux
      env: BUILD_TARGET=android_cmake
      language: android
      sudo: true
      android:
        components:
          - tools
          - platform-tools
          - build-tools-27.0.3
          - android-28
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-android-support
          - extra-google-google_play_services
    - os: osx
      env: BUILD_TARGET=mac_cmake
      language: cpp
      osx_image: xcode9.4
      sudo: true
    - os: osx
      env: BUILD_TARGET=ios_cmake
      language: cpp
      osx_image: xcode9.4
      sudo: true

before_install:
  - travis/before-install.sh

script:
  - travis/run-script.sh

cache: 
  bundler: true
  directories:
    - $HOME/cocos2d-x-3.17.1
